CHIP_SPAM_TESTING_CHANNEL_ID = "C03HA2B21RP"

'''For security reasons - to not search any sensitive info during the DEMO, we are only whitelisting few public slack groups'''
RIPPLING_GENERAL_CHANNEL_ID = "C026U3NMPPZ"
RIPPLING_BANGALORE_CHANNEL_ID = "C5FNMR8MC"
RIPPLING_CDE_CHANNEL_ID = "C02AJAS27V5"
RIPPLING_CONTACT_INFRA_CHANNEL_ID = "CKC49MGLD"
RIPPLING_RANDOM_CHANNEL_ID = "C1NA905DL"
RIPPLING_WHITELIST_CHANNELS = [RIPPLING_GENERAL_CHANNEL_ID, RIPPLING_BANGALORE_CHANNEL_ID, RIPPLING_CDE_CHANNEL_ID,
                            RIPPLING_CONTACT_INFRA_CHANNEL_ID, RIPPLING_RANDOM_CHANNEL_ID]
